ERROR 2025-03-13 15:25:30,337 log Internal Server Error: /django/admin/partners/countrydirectionrate/
Traceback (most recent call last):
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column partners_countrydirectionrate.rate_coefficient does not exist
LINE 1: ..."partners_countrydirectionrate"."max_rate_limit", "partners_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2065, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column partners_countrydirectionrate.rate_coefficient does not exist
LINE 1: ..."partners_countrydirectionrate"."max_rate_limit", "partners_...
                                                             ^

ERROR 2025-03-13 15:28:19,809 log Internal Server Error: /django/admin/partners/countrydirectionrate/
Traceback (most recent call last):
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column partners_countrydirectionrate.rate_coefficient does not exist
LINE 1: ..."partners_countrydirectionrate"."max_rate_limit", "partners_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2065, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column partners_countrydirectionrate.rate_coefficient does not exist
LINE 1: ..."partners_countrydirectionrate"."max_rate_limit", "partners_...
                                                             ^

ERROR 2025-03-13 15:30:10,678 log Internal Server Error: /django/admin/partners/countrydirection/
Traceback (most recent call last):
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column partners_countrydirectionrate.rate_coefficient does not exist
LINE 1: ..."partners_countrydirectionrate"."max_rate_limit", "partners_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1959, in changelist_view
    response = self.response_action(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1593, in response_action
    response = func(self, request, queryset)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/actions.py", line 39, in delete_selected
    ) = modeladmin.get_deleted_objects(queryset, request)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2101, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 121, in get_deleted_objects
    collector.collect(objs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 187, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/deletion.py", line 348, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 412, in __bool__
    self._fetch_all()
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/skxnny/web/moneyswap_back/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column partners_countrydirectionrate.rate_coefficient does not exist
LINE 1: ..."partners_countrydirectionrate"."max_rate_limit", "partners_...
                                                             ^

